### ISSUE TITLE
Vpred models broken in latest version

### ISSUE THREAD

**Issue by PseudoChmod** [lllyasviel/stable-diffusion-webui-forge#1241] opened 2024-08-17 18:19 UTC
As title says, vpred models don't load correctly in the latest update and generate heatmap images. The previous build [cu121_torch21_f0017](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/previous) works fine and can load any models without issues, but upon updating only regular eps SD1/1.5/2 and SDXL models work.

**Comment by mkgiga** [comment] 2024-08-23 20:41
Confirming this, also have the same problem

**Comment by AlexA1S** [comment] 2024-08-24 08:44
Also confirming this too.

**Comment by NoCarryingHere** [comment] 2024-09-01 15:53
Also confirming this.

**Comment by KiraSlith** [comment] 2024-09-10 21:26
That's VERY broken...
![00028-2991771697](https://github.com/user-attachments/assets/5a44578d-b13d-44d2-b585-d54ae096d6b1)
![00003-711122163](https://github.com/user-attachments/assets/c0896a82-0d4a-47a6-aad2-8a89eedc21e4)

**Comment by PseudoChmod** [comment] 2024-09-24 19:12
Currently hasn't been fixed as of latest update, is anything being done to fix this? ReForged works fine but I'd like the performance/support of the latest Forge version.

**Comment by geriberton** [comment] 2024-09-25 22:32
Same issue for me.

**Comment by Darkenlord1** [comment] 2024-10-16 12:20
same

**Comment by catboxanon** [comment] 2024-10-18 19:19
Duplicate of https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1109

**Closed by catboxanon** 2024-10-18 19:19 UTC
Labels: bug
