### ISSUE TITLE
Prompt forwarding is not working (*When installing and updating using Git clone & Git pull) 

### ISSUE THREAD

**Issue by mimimi999** [lllyasviel/stable-diffusion-webui-forge#880] opened 2024-07-28 09:09 UTC
Prompt forwarding is not working for all patterns.
(png info→tex2img,img2img)

I think I have the latest version of forge because I did a clean install, but is there a solution? 

•  version: [f1.0.1v1.10.1rc-previous-22-g6eb23c6d]
 •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 4.39.0  •  checkpoint: [67ab2fd8ec]

**Comment by GvandivaGi** [comment] 2024-07-28 09:12
Same here and all my extensions are not working. I updated Forge to the latest version today. Any fixes? Thank you.

**Comment by wzwow** [comment] 2024-07-28 12:03
even fresh install, many extension become broken.

**Comment by lllyasviel** [comment] 2024-07-28 14:26
i cannot reproduce?

**Comment by mimimi999** [comment] 2024-07-28 15:07
My information was incorrect. sorry.
tex2img→img2img＆inpaint is working properly.

The problem is the information transfer from PNG info.
Things like generation size and seeds are transferred, but prompts are not.

I installed using Git clone without any installation packages, are they relevant?

https://github.com/user-attachments/assets/a8dc3c48-5a54-48b3-96aa-9a2f6bc2dd0d

**Comment by Dreamz-Dziner** [comment] 2024-07-28 18:29
Yes the prompt forwarding isn't doing anything. Something seems broken.

**Comment by mimimi999** [comment] 2024-07-29 03:14
> i cannot reproduce?

I did some tests.

(① Install forge using the installation package)
After updating, the prompt forwarding function is working without problems with the latest version of forge.

(② Install forge using Git Clone & update with Git pull)
This installation method causes a problem with the prompt forwarding function.

*The title of the post has been changed because it seems that not all users are experiencing the same error.

**Comment by GvandivaGi** [comment] 2024-07-29 03:17
> > i cannot reproduce?
> 
> I did some tests.
> 
> (① Install forge using the installation package) After updating, the prompt forwarding function is working without problems with the latest version of forge.
> 
> (② Install forge using Git Clone & update with Git pull) This installation method causes a problem with the prompt forwarding function.
> 
> *The title of the post has been changed because it seems that not all users are experiencing the same error.

Yes, I did install Forge with Git Clone and updated It yesterday with Git pull.

**Comment by CoffinOfMyLife** [comment] 2024-07-29 03:56
I seem to have fixed by replacing 
```
"txt2img/Prompt/visible": true,
    "txt2img/Prompt/value": null,
    "txt2img/Negative prompt/visible": true,
    "txt2img/Negative prompt/value": null,
```
with
```
    "txt2img/Prompt/visible": true,
    "txt2img/Prompt/value": "",
    "txt2img/Negative prompt/visible": true,
    "txt2img/Negative prompt/value": "",
```
in ui-config.json

**Comment by Dreamz-Dziner** [comment] 2024-07-29 05:12
> > i cannot reproduce?
> 
> I did some tests.
> 
> (① Install forge using the installation package) After updating, the prompt forwarding function is working without problems with the latest version of forge.
> 
> (② Install forge using Git Clone & update with Git pull) This installation method causes a problem with the prompt forwarding function.
> 
> *Both versions are tested after updating to the latest version (version: f1.0.2v1.10.1-previous-26-g37386592). *The title of the post has been changed because it seems that not all users are experiencing the same error.

Tried the installation using the package and the prompt forwarding is working. But once we start using controlnet the models were not getting loaded properly so I had to manually download the repo files(zip) and overwrite the "webui" folder inside the package. Now everything seems to be fine.

**Comment by mimimi999** [comment] 2024-07-29 05:25
> > > i cannot reproduce?
> > 
> > 
> > I did some tests.
> > (① Install forge using the installation package) After updating, the prompt forwarding function is working without problems with the latest version of forge.
> > (② Install forge using Git Clone & update with Git pull) This installation method causes a problem with the prompt forwarding function.
> > *Both versions are tested after updating to the latest version (version: f1.0.2v1.10.1-previous-26-g37386592). *The title of the post has been changed because it seems that not all users are experiencing the same error.
> 
> Tried the installation using the package and the prompt forwarding is working. But once we start using controlnet the models were not getting loaded properly so I had to manually download the repo files(zip) and overwrite the "webui" folder inside the package. Now everything seems to be fine.

It seems that the problem of control net failure has been confirmed for some time.
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/849

**Comment by mimimi999** [comment] 2024-07-29 06:54
> I seem to have fixed it by replacing
> 
> ```
> "txt2img/Prompt/visible": true,
>     "txt2img/Prompt/value": null,
>     "txt2img/Negative prompt/visible": true,
>     "txt2img/Negative prompt/value": null,
> ```
> 
> with
> 
> ```
>     "txt2img/Prompt/visible": true,
>     "txt2img/Prompt/value": "",
>     "txt2img/Negative prompt/visible": true,
>     "txt2img/Negative prompt/value": "",
> ```
> 
> in ui-config.json

(If you cannot use the prompt transfer function when installing using git clone)
It seems easy to rewrite the json file described in the comment.

① Open the 「ui-config.json」 file with Notepad, etc.
② Rewrite the 3rd and 5th lines as shown in the image and save.

Now prompt forwarding functions such as png info will work properly.

![1](https://github.com/user-attachments/assets/1d727759-ea16-46ab-a36b-57277ca9434a)
![2](https://github.com/user-attachments/assets/9d3eebdb-643e-4de1-b3c0-71d578ebbf89)

**Closed** 2024-07-29 15:22 UTC
Labels: Under Construction
