### ISSUE TITLE
reactor not working after update

### ISSUE THREAD

**Issue by Kasukus** [lllyasviel/stable-diffusion-webui-forge#906] opened 2024-07-31 08:35 UTC
2024-07-31 13:57:07.4381847 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\webui_forge_cu121_torch21\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

tried to install forge again. but the same problem coming after installing reactor

**Comment by dongxiat** [comment] 2024-07-31 15:55
install Reactor is fine.... but... function not working 
just tested

**Comment by DenOfEquity** [comment] 2024-07-31 23:46
Reactor is working for me, though I did have to go the **Settings** tab (in Reactor extension, not main webUI settings) and set the **Execution Provider**. Before doing that, I was getting same error as Kasukus. Tested from image and from face model.
See also [this issue](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/889) to fix the **Select Source** radio buttons.

**Comment by Kasukus** [comment] 2024-08-01 02:55
how to go to the settings on reactor extension? can u help me

**Comment by Kasukus** [comment] 2024-08-01 02:58
i checked the Execution Provider and its gpu

**Comment by Kasukus** [comment] 2024-08-01 02:58
sorry its cuda

**Comment by DenOfEquity** [comment] 2024-08-01 09:54
The error message hints that the problem is CUDA related, so set ReActor to use CPU then press the Save button and restart if necessary. You should find that speed using CPU is fine. Takes a couple of seconds on my old laptop; about same as using CUDA.
I believe the error is related to onnxruntime version not matching CUDA version. If you have another webUI where ReActor does work using CUDA, you can simply copy that .dll mentioned in the error message across. That's what I did this time, copied from old Forge into fresh install of new Forge.
Alternatively, try temporarily installing a different face swap extension to see if that sets up the onnxruntime correctly. I remember I had to do that months ago, when I first tried ReActor.

**Comment by Kasukus** [comment] 2024-08-01 12:35
thank u my dear friend ..... i will try .... thanks a lot

**Comment by Kasukus** [comment] 2024-08-01 12:42
i switched to cpu mode, and its working fine as cuda. but all other features like remove background, that works using cuda is not working at the moment. I hope your imagination is right. some way onnxruntime version is not supporting cuda right now. I tried to uninstall cuda and install it again, but no luck.

**Comment by Kasukus** [comment] 2024-08-01 18:13
anyway i copied onnxruntime_providers_cuda.dll file that works perfect on my other forge version into my new forge, and now its working fine on cuda also. thank u so much dear friend DenOfEquity to sort out this problem to me.

**Comment by dramatticdev** [comment] 2024-08-02 02:25
I have gotten it to work 100 percent as it should and using cuda as normal by simply adding these 2 lines to the requirements file for reactor
onnxruntime==1.18.1
onnxruntime-gpu==1.18.1

the file is located in
\webui\extensions\sd-webui-reactor

**Comment by Kasukus** [comment] 2024-08-02 08:00
thank you dramatticdev. it works for me.

**Comment by Adpack82** [comment] 2024-08-02 12:19
Thanks, dramatticdev. sorted for me too!

**Comment by altoiddealer** [comment] 2024-08-05 14:56
> thank you dramatticdev. it works for me.

This Issue should be marked as solved.

The error is with the ReActor extension, not exclusive to Forge.



> I have gotten it to work 100 percent as it should and using cuda as normal by simply adding these 2 lines to the requirements file for reactor onnxruntime==1.18.1 onnxruntime-gpu==1.18.1
> 
> the file is located in \webui\extensions\sd-webui-reactor


THANKS!!!! You've ended my suffering!

**Closed** 2024-09-15 22:37 UTC
