### ISSUE TITLE
New update cannot select VAE

### ISSUE THREAD

**Issue by cuom1705** [lllyasviel/stable-diffusion-webui-forge#1076] opened 2024-08-14 02:24 UTC
![image](https://github.com/user-attachments/assets/cab4781c-dacc-408d-ab3b-d619faa76317)
Cannot select VAE/Text Encoder from quick setting. Dropdown list doesnt show up, text input doent work.

**Comment by AllInOneMighty** [comment] 2024-08-14 02:28
Yup. Same here.

**Comment by pflky** [comment] 2024-08-14 02:55
if you're sharing folders with A1111 and you don't have a launch flag for VAE location, then it'll use the Forge location. So moving that to the Forge directory could work, if that's the problem.

**Comment by freecoderwaifu** [comment] 2024-08-14 03:23
For now move or copy your VAEs to `models\text_encoder`, text encoders also go there obviously. This is something that hopefully will get fixed for VAEs.

**Comment by cuom1705** [comment] 2024-08-14 03:34
Thank you guys. 
I solved this problem. 
`--vae-dir ` causes the problem, it cannot override the default path when launch. So I make a symbolic link to my VAE folder.

**Comment by lucyanim** [comment] 2024-08-14 09:44
where and how,I add --vae-dir “D:\forge\stable-diffusion-webui-forge\models\VAE” in webuser.bat still can not select

**Comment by alesimula** [comment] 2024-08-14 12:33
Also there should be at least an "Auto" option, even with no VAEs

**Comment by ostap667inbox** [comment] 2024-08-14 22:48
Yes, --vae-dir parameter is broken now, no items in VAE/Text encoder drop-down menu.

**Comment by diversk** [comment] 2024-08-15 01:40
Thanks to Illyasviel,I confirmed this issue has been fixed at commit "df0fee"
`--vae-dir` arguments is functional now.

**Comment by a3nima** [comment] 2024-08-15 12:55
I'm using symlink, and it works for models, text-encoder etc. everywhere but in the VAE folder it doesn't seem to work. Any ideas?

**Comment by bkosowski** [comment] 2024-09-15 11:42
@cuom1705 should be working fine now. Please check and close the issue if so.

**Closed** 2024-09-15 22:28 UTC

**Comment by rami-daoud** [comment] 2024-10-27 18:02
after fresh clean install on mac mini m2 pro the VAE / Text Encoder dropdownlist automatic value  is missing
![Screen Shot 2024-10-27 at 19 01 38 PM](https://github.com/user-attachments/assets/59eaf0e5-28fa-41ec-9a81-295ba415aca0)
 by default.

**Comment by VL4DST3R** [comment] 2025-02-04 23:51
I came looking to report the same thing as the user above. Switched to Forge ui from A1111 and noticed that there is no "automatic" option for vae anymore, and there is no info about if it should be used differently now.

**Comment by df917** [comment] 2025-04-08 19:59
Same issue with downloaded releases, someone have a fix ?

**Comment by VL4DST3R** [comment] 2025-04-08 20:05
@df917 I believe you should make a new issue to bring the issue back into focus, nobody seems to be following this thread anymore.
